In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])
twoD=arr.reshape(3,3)
print("1D array :: \n", arr, "\n 2D array ::\n", twoD )

1D array :: 
 [1 2 3 4 5 6 7 8 9] 
 2D array ::
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
