In [2]:
import numpy as np

In [13]:
X=np.array([ [1,2,3],[4,5,6],[7,8,9]])
Y=np.array([[10,11,12],[13,14,15],[15,17,18]])
print("Array A: \n\t Vertical stacking:: \n",np.vstack(X),"\n\n\tHorizontal stacking::\n ", np.hstack(X),"\n")
print("Array B: \n\t Vertical stacking:: \n",np.vstack(Y),"\n\n\tHorizontal stacking:: \n", np.hstack(Y),"\n")

Array A: 
	 Vertical stacking:: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

	Horizontal stacking::
  [1 2 3 4 5 6 7 8 9] 

Array B: 
	 Vertical stacking:: 
 [[10 11 12]
 [13 14 15]
 [15 17 18]] 

	Horizontal stacking:: 
 [10 11 12 13 14 15 15 17 18] 

