In [3]:
import numpy as np

In [9]:
l1=[]
l2=[]
print("Enter 5 elements in list 1::")
for i in range(0, 5):
    item1 = int(input())
    l1.append(item1)
print("Enter 5 elements in list 2::")
for i in range(0, 5):
    item2 = int(input())
    l2.append(item2)    
print("List 1:",l1)  
print("List 2:",l2)
print("\n")

#converting list into numpy array
arr1= np.array(l1)
print(arr1)
arr2= np.array(l2)
print(arr2)
print("\n")

#Concatenate these arrays
arr=np.concatenate((arr1, arr2))
print("Concatenating arrays:\n ",arr)
print("\n")

#sorting of arrays
print("Sorted arrays ::\n",np.sort(arr1), "\n", np.sort(arr2))

Enter 5 elements in list 1::
2
3
4
5
6
Enter 5 elements in list 2::
8
5
1
2
6
List 1: [2, 3, 4, 5, 6]
List 2: [8, 5, 1, 2, 6]


[2 3 4 5 6]
[8 5 1 2 6]


Concatenating arrays:
  [2 3 4 5 6 8 5 1 2 6]


Sorted arrays ::
 [2 3 4 5 6] 
 [1 2 5 6 8]
